### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nefilim** [user-signal/fs2-mqtt#170]
Hi - nice project! could you please create a new release with all the steward updates since the last release in 2022?

**Comment by fcabestre** [comment]
I was not aware anyone is using this library and I quite glad of it. I'd be pleased to create this new release, but at the moment I'm struggling with the `ZIO` based example. And as each time I struggle with `ZIO` I may drop this example and replace it with a plain `Cats Effect` one. So stay tuned...

**Comment by nefilim** [comment]
Thank you! I use cats effect too fwiw. I may be the only person on the internet doing home automation in Scala 😅

**Comment by fcabestre** [comment]
The release `1.0.1` integrating last steward updates (and a bit more) is available. You can check that at https://central.sonatype.com/artifact/net.sigusr/fs2-mqtt_3. Enjoy!

By the way I don't envision to spend much time working on this library, but apart from improvements if you you find anything blocking I'll be glad to hear about it.
